/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.verify;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author SHANMA
 */
public class EditUsers extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditUsers
     */
    public EditUsers() {
        DBConnection.connect();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        acctype = new javax.swing.JComboBox();
        update = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        editUser = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Edit User Information");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Edit24.gif"))); // NOI18N
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 102, 51));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 370, 10));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)), "UserID", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tempus Sans ITC", 1, 14), java.awt.Color.darkGray)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("User Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        edit.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        edit.setText("Validate");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 90, -1));

        username.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 190, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 290, 110));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("EDIT USER INFORMATION");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        exit.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        exit.setText("Cancel");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 80, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)), "User Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tempus Sans ITC", 1, 14), java.awt.Color.darkGray)); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("User Name");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        jLabel5.setText("User Accout-type");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        acctype.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        acctype.setForeground(java.awt.Color.darkGray);
        acctype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select...", "ADMIN", "TECH USER", "USER" }));
        jPanel3.add(acctype, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 130, 30));

        update.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        update.setText("Update the Information");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel3.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 170, -1));

        refresh.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel3.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        editUser.setEditable(false);
        editUser.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel3.add(editUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 190, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 290, 160));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
        this.hide();
    }//GEN-LAST:event_exitActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try{
            if(username.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Empty field, retry", 
                    "Empty field", JOptionPane.OK_OPTION);
            }else{ 
                String sql1= "select * from User where Username='"+username.getText()+"'";
                DBConnection.rs= DBConnection.st.executeQuery(sql1);     
                if(DBConnection.rs.next()){
                    editUser.setText(DBConnection.rs.getString("Username"));
                    acctype.setSelectedItem(DBConnection.rs.getString("Usertype"));
                    edit.setEnabled(false);
                }else{
                    JOptionPane.showMessageDialog(this, "User does not exist", 
                        "User Not found", JOptionPane.OK_OPTION);
                    editUser.setText("");
                    acctype.setSelectedIndex(0);
        
                }
            }
        }catch(Exception ex){
            System.out.println(ex.fillInStackTrace());
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_editActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        username.setText("");
        editUser.setText("");
        acctype.setSelectedIndex(0);
        edit.setEnabled(true);
    }//GEN-LAST:event_refreshActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try{
            if(editUser.getText().equals("") || acctype.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(this, "Empty fields, retry", 
                    "Empty fields", JOptionPane.OK_OPTION);
            }else if(DBConnection.rs!=null){
                String sql= "update User set Usertype='"+acctype.getSelectedItem()+"' where Username='"+username.getText()+"'";
                DBConnection.st.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Information Updated", 
                    "Updated", JOptionPane.INFORMATION_MESSAGE);
                acctype.setSelectedIndex(0);
                username.setText("");
                editUser.setText("");
                edit.setEnabled(true);
            }   
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox acctype;
    private javax.swing.JButton edit;
    private javax.swing.JTextField editUser;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton refresh;
    private javax.swing.JButton update;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
