/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.verify;

import static com.verify.MainMenu.desktop1;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author NUHU
 */
public class ResultSign extends javax.swing.JInternalFrame {

    /**
     * Creates new form Result
     */
    SignInVerifyBio main;
    public ResultSign(SignInVerifyBio main) {
        this.main = main;
        DBConnection.connect();
        initComponents();
        try{
            PreparedStatement st;
            String sql1= "select * from student_pass where reg_no=?";
            st = DBConnection.con.prepareStatement(sql1);
            
            st.setString(1, main.main.getRegNo());
            DBConnection.rs= st.executeQuery();
            if (DBConnection.rs.next()){
                Icon iicon= new ImageIcon(DBConnection.rs.getString("passport"));
                me1.setIcon(iicon);
                
                regNum1.setText(DBConnection.rs.getString("reg_no"));
                fname.setText(DBConnection.rs.getString("fname"));
                mname.setText(DBConnection.rs.getString("mname"));
                lname.setText(DBConnection.rs.getString("lname"));
                gender.setText(DBConnection.rs.getString("gender"));
                level.setText(DBConnection.rs.getString("level"));
                program.setText(DBConnection.rs.getString("dept"));
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        me2 = new javax.swing.JLabel();
        me1 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        regNum1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mname = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        program = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Verification Result");
        setPreferredSize(new java.awt.Dimension(503, 537));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tempus Sans ITC", 1, 14), java.awt.Color.darkGray)); // NOI18N
        jPanel6.setMaximumSize(new java.awt.Dimension(150, 150));
        jPanel6.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel6.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(me2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 20));

        me1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                me1PropertyChange(evt);
            }
        });
        jPanel6.add(me1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 150, 150));

        update.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        update.setText("Ok");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 190, -1));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Verification Result Page");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/images.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, 160));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 0));
        jLabel10.setText("Registration Number");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 30));

        fname.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        fname.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 310, 30));

        regNum1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        regNum1.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(regNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 310, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("Firstname");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 0));
        jLabel7.setText("Middlename");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 30));

        mname.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        mname.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 310, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 0));
        jLabel8.setText("Lastname");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 30));

        lname.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lname.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 310, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 0));
        jLabel9.setText("Level");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 110, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 0));
        jLabel12.setText("Course of Study");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, 30));

        program.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        program.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(program, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 310, 30));

        level.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        level.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 310, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 50, 30));

        gender.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        gender.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 310, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void me1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_me1PropertyChange
        
    }//GEN-LAST:event_me1PropertyChange
    
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try{
            java.util.Date date = new java.util.Date();
            String d1 = new SimpleDateFormat("yyyy-MM-dd").format(date);
            String start = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(date);
            String sign_in = new SimpleDateFormat("HH:mm:ss").format(date);

            PreparedStatement st;
            String sql1= "select * from exam_info where exam_id = ?";
            st = DBConnection.con.prepareStatement(sql1);
            st.setString(1, main.main.getExamId());

            DBConnection.rs = st.executeQuery();
            DBConnection.rs.next();
            String end  = DBConnection.rs.getString("end_time");
            d1 = DBConnection.rs.getString("exam_date");

            date = new java.util.Date(d1.replaceAll("-", "/")+" "+end);
            end = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(date);

            String sign_out = new SimpleDateFormat("HH:mm:ss").format(date);

            String sql = "insert into exam_sign_in (exam_id, reg_no, sign_in_time, sign_out_time, sign_in, sign_out) values (?,?,?,?,?,?)";
            st = DBConnection.con.prepareStatement(sql);
            st.setString(1, main.main.getExamId());
            st.setString(2, main.main.getRegNumb());
            st.setString(3, start);
            st.setString(4, end);
            st.setString(5, sign_in);
            st.setString(6, sign_out);

            st.executeUpdate();

            JOptionPane.showMessageDialog(this, "Student signed in successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            this.hide();
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        Thread runner = new Thread() {

        public void run() {
            ExamSignIn regJ = new ExamSignIn();
            desktop1.add(regJ);
            try {
                regJ.setSelected(true);
            } catch (java.beans.PropertyVetoException e) {
            }
            }
        };
        runner.start();
    }//GEN-LAST:event_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fname;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel level;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel me1;
    private javax.swing.JLabel me2;
    private javax.swing.JLabel mname;
    private javax.swing.JLabel program;
    private javax.swing.JLabel regNum1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
